### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by semisight** [paolobtl/gtm-template-tawkto-widget#1]
https://github.com/paolobtl/gtm-template-tawkto-widget/blob/e8083e8001c2d4971ee831e44690adb8261c2c95/template.tpl#L78

When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by paolobtl** [comment]
> https://github.com/paolobtl/gtm-template-tawkto-widget/blob/e8083e8001c2d4971ee831e44690adb8261c2c95/template.tpl#L78
> 
> When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

Thank you!
Fixed in commit 5d71adc47f1e667bdd68087e8ac96581224aaadd

**Comment by paolobln** [comment]
Hi @semisight any chance to have this template published?
